---
# Disable C-states
- name: Disable C-states
  block:
    - name: Check if C-states are already disabled
      command: grep 'intel_idle.max_cstate=0 processor.max_cstate=0' /etc/default/grub
      register: cstates_check
      changed_when: false
      failed_when: false

    - name: Fail if C-states are already disabled
      fail:
        msg: "ERROR: C-states are already disabled in GRUB!"
      when: cstates_check.rc == 0

    - name: Disable C-states permanently
      replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=")([^"]*)"'
        replace: '\1\2 intel_idle.max_cstate=0 processor.max_cstate=0"'

    - name: Update GRUB configuration
      command: update-grub
      when: ansible_os_family == "Debian"

    # Mark system for reboot
    - name: Mark system for reboot
      set_fact:
        global_reboot_required: true
  rescue:
    - name: Show error
      fail:
        msg: "Stage 'cpu_config: Disable C-states' couldn't be passed"
