---
- name: Change network interface name
  block:
    # Detect active network interface
    - name: Detect active network interface
      shell: "ip route | grep default | awk '{print $5}'"
      register: detected_interface
      changed_when: false

    - name: Set detected interface as variable
      set_fact:
        net_interface: "{{ detected_interface.stdout }}"

    # Compare current name and new one
    - name: Compare current name and new one
      fail:
        msg: "Network interface is already named correctly"
      when: detected_interface.stdout == new_name_net_interface

    # Create systemd.link file
    - name: Create systemd.link configuration file
      template:
        src: systemd_link.j2
        dest: "/etc/systemd/network/10-{{ new_name_net_interface }}.link"
        mode: "0644"

    # Reload systemd network configuration
    - name: Reload systemd-udevd
      command: systemctl restart systemd-udevd

    # Mark for reboot
    - name: Mark system for reboot
      set_fact:
        global_reboot_required: true

  rescue:
    - name: Show error
      fail:
        msg: "Stage 'network_config' couldn't be passed"
      ignore_errors: true
