---
- name: Server Preparation
  hosts: all
  become: true
  vars:
    global_reboot_required: false
    roles_all: []
    roles_failed: []
  vars_files:
    - vault.yml
  roles:
    - encrypt_disk
    - cpu_config
    - network_config

  post_tasks:
    - name: Reboot the server if required
      reboot:
        reboot_timeout: 300
      when: global_reboot_required | bool

    - name: Run cpu_info role
      include_role:
        name: cpu_info

    - name: Generate roles_successful
      set_fact:
        roles_successful: "{{ roles_all | difference(roles_failed) }}"
      no_log: true

    - name: Show summary of executed roles
      debug:
        msg: "{{ ['✅ Successful Roles:'] + roles_successful}}"

    - name: Show summary of executed roles
      debug:
        msg: "{{ ['❌ Failed Roles:'] + roles_failed}}"
