---
- name: Server Preparation
  hosts: all
  become: true
  any_errors_fatal: false
  vars:
    global_reboot_required: false
  vars_files:
    - vault.yml
  roles:
    - { role: encrypt_luks_device, ignore_errors: true }
    # - {role: encrypt_partition, ignore_errors: true}
    - { role: cpu_frequency_scaling, ignore_errors: true }
    - { role: cpu_disable_cstates, ignore_errors: true }
    - { role: network_config, ignore_errors: true }

  post_tasks:
    - name: Reboot the server if required
      reboot:
        reboot_timeout: 600
      when: global_reboot_required | bool
      changed_when: false

    - name: Run cpu_info role
      include_role:
        name: cpu_info
